### ISSUE TITLE
Something's weird with layer mask

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#150]
When I try to fit a compound model (Gaussian + Const) to Gisella's MDM data subset (selected with the ROI thingy), I always get this:
```python
.../specviz/core/data.py:218: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1161 but corresponding boolean dimension is 130
  return Quantity(self._source.dispersion[self._mask],
```

I don't think `ModelLayer` is handling mask properly. @ibusko ?

**Comment by ibusko** [comment]
I can't reproduce the error. Maybe it has to do with the exact placement of the ROI or something. I am using the default ROI that pops up when we click on the rectangle icon atop the plot.

**Comment by pllim** [comment]
This is my ROI (using one of Gisella's MDM test data):
![screenshot](https://cloud.githubusercontent.com/assets/2090236/13333490/56434e7a-dbd5-11e5-9521-76b667081e37.png)

This is my traceback when I perform a fit within the ROI:
```python
.../astropy/units/quantity.py:894: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 145 but corresponding boolean dimension is 1161
  out = super(Quantity, self).__getitem__(key)
Traceback (most recent call last):
  File ".../specviz/ui/controller.py", line 380, in fit_model_layer
    fitter_name=self.viewer.current_fitter)
  File ".../specviz/interfaces/managers.py", line 368, in fit_model
    flux = parent_layer.data[mask]
  File ".../astropy/units/quantity.py", line 894, in __getitem__
    out = super(Quantity, self).__getitem__(key)
IndexError: index 506 is out of bounds for axis 1 with size 145
```

**Comment by ibusko** [comment]
Again, I can't reproduce the error. It runs for me, although I get a bad fit if I don't tweak the parameters by hand. In cases like this (narrow features) the ability to place constraints on the fitter is badly needed. The fitter may easily go bonkers and produce solutions where then gaussian 'mean' lies outside the ROI, or solutions where fwhm is negative. You have to have your first guesses pretty close to the actual values, especially for the gaussian mean.

**Comment by pllim** [comment]
I just updated my astropy to the latest dev, and I see the error. I am using RHEL6, Anaconda with Qt4. Although I really can't see why Qt version or OS would matter in this case.

**Comment by pllim** [comment]
I mean, I see that the fit went bonkers as well. But in addition to that, I also see the traceback in the terminal. Did you not see anything printed out at all?

**Comment by nmearl** [comment]
I'm not getting anything printed out either. Which MDM data specifically are you using?

**Comment by pllim** [comment]
I looked at Ivo's screen at the tag up, and saw that he didn't see what I saw. He was using Mac, Qt5, Anaconda, Astropy 1.1.1 (not dev). Very weird.

But I also noticed that you and Ivo always run it out of IDE (PyCharm). I run it from a regular Unix terminal outside the source tree.

**Comment by nmearl** [comment]
I see it now. Just had to do some steps to make it appear:

1. Load Gisella's data, select @pllim's region shown above
2. Add Linear and Gaussian models
3. Perform fit (the fit is perfect the first time on my screen)
4. Remove models from list
5. Add Linear and Gaussian models again
6. See error in log.

Looking at the code, @ibusko, you're applying the layer mask twice:

```python
mask = parent_layer._mask
flux = parent_layer.data[mask]
dispersion = parent_layer.dispersion[mask]
```

When you call `parent_layer.data` and `parent_layer.dispersion`, the `parent_layer._mask` is already applied:

```python
@property
def dispersion(self):
    """Dispersion quantity with mask applied."""
    return Quantity(self._source.dispersion[self._mask],
                    unit=self._source.dispersion_unit).to(self.units[0])
```

**Comment by pllim** [comment]
Bravo, @nmearl ! It is good to know I'm not going crazy. :smile: :clap:

**Comment by nmearl** [comment]
> Bravo, @nmearl ! It is good to know I'm not going crazy. :smile: :clap:

:tada: 

Also, it seems like it's not the fitting that triggers the error, the error pops up at step 5. As soon as you add the model, the error appears.

**Comment by ibusko** [comment]
OK, I removed the redundant mask application. Try it now.

**Comment by nmearl** [comment]
Still didn't work. I've pushed a commit that fixes it though.

**Comment by nmearl** [comment]
The problem seemed to be when you ran your initializers:

```python
# initialize model with sensible parameter values.
# mask must be provided by caller, since ROIs may
# have been re-defined on the plot since last time
# the layer was updated.
flux = data_layer.data[mask]
dispersion = data_layer.dispersion[mask]
initialize(model, dispersion, flux)
```

In the case where the `ModelLayer` hadn't been created, your `mask` object was rightly created from the `Layer` object and applied to the flux and dispersion of the `Layer` object. However, when the `ModelLayer` already exists and you add a new model object, you're grabbing the mask of the `ModelLayer` but applying it to its parent, the original `Layer`. In this case, the mask bounds are that of the parent `Layer`, but the flux and dispersion are the size of the `ModelLayer`.

**Comment by ibusko** [comment]
OK, that seems to have fixed it! Thanks for clarifying how the layers and masks interact with each other. That probably explains why I was sometimes getting unphysical solutions such as negative fwhm and the like.

**Comment by pllim** [comment]
I still see this traceback:
```python
.../specviz/core/data.py:232: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 1161 but corresponding boolean dimension is 145
  return Quantity(self._source.dispersion[self._mask],
```

But my workflow is slightly different from what Ivo is showing right now in the tag-up. That is, I create the additional layer first and then attach models to the second layer:
![untitled](https://cloud.githubusercontent.com/assets/2090236/13365594/ecf0c6f8-dca3-11e5-94fd-df0cb11c63b7.png)
